# cloudbuild.yaml
substitutions:
  _IMAGE: "asia-northeast1-docker.pkg.dev/$PROJECT_ID/containers/vm-ctrl:latest"

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]

# ここに指定したイメージは、build 完了時に Cloud Build が自動で push します
images:
  - "${_IMAGE}"
