substitutions:
  _PROJECT_ID: "pure-loop-470510-a7"   # ← 自分のプロジェクトIDを直接書く
  _IMAGE: "asia-northeast1-docker.pkg.dev/${_PROJECT_ID}/containers/vm-ctrl:latest"

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]

images:
  - "${_IMAGE}"

options:
  logging: CLOUD_LOGGING_ONLY
